# Generated by Django 2.0.2 on 2018-03-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='TestUsers',
        ),
    ]
