# Generated by Django 2.0.2 on 2018-03-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180308_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testusers',
            old_name='lastNAme',
            new_name='lastName',
        ),
    ]
